site_name: Poolshark Docs
# site_description: 'Develop, Release and Operate Container Apps on AWS.'
site_url: https://poolsharks-protocol.github.io/oceanbook-docs/
repo_name: 'GitHub'
repo_url: 'https://github.com/poolsharks-protocol/oceanbook-docs/'
edit_uri: '/poolsharks-protocol/docs/tree/main/site/content'
copyright: 'Written by Poolshark Labs'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.en.md
  - Introduction: 
    - What is Poolshark?: docs/intro/index.en.md
    - Cover Pools: docs/intro/limitations-of-amms.en.md
    - Price Pools: docs/intro/limitations-of-clobs.en.md
    - Range Pools: docs/intro/limitations-of-clobs.en.md
    - Tokenomics Overview: docs/intro/launch.en.md
  - Protocol Guide:
    - Liquidity Types:
        - Directional Liquidity: docs/liquidity-providers/directional-liquidity.en.md
        - Cover Liquidity: docs/liquidity-providers/single-sided.en.md
        - Price Liquidity: docs/liquidity-providers/directional-range-order.en.md
        - Range Liquidity: docs/liquidity-providers/concentrated-liquidity.en.md
    - Swaps: docs/protocol-guide/swaps.en.md
    - Mints: docs/protocol-guide/mints.en.md
    - Burn: docs/protocol-guide/burn.en.md
    - Fees: docs/protocol-guide/fees.en.md
    - Oracles: docs/protocol-guide/oracles.en.md
  - Smart Contracts:
      - Overview: docs/smart-contracts/overview.en.md
      - Base: 
          - PoolsharkCoverPairFactory: docs/smart-contracts/base/PoolsharkBookFactory.en.md
          - PoolsharkCoverPair: docs/smart-contracts/base/PoolsharkBook.en.md
          - PoolsharkPricePairFactory: docs/smart-contracts/base/PoolsharkPairFactory.en.md
          - PoolsharkPricePair: docs/smart-contracts/base/PoolsharkPair.en.md
          - PoolsharkRangePairFactory: docs/smart-contracts/base/PoolsharkQueueFactory.en.md
          - PoolsharkRangePair: docs/smart-contracts/base/PoolsharkQueue.en.md
      - Libraries:
          - DyDxMath: docs/smart-contracts/libraries/LiquidityMath.en.md
          - FullPrecisionMath: docs/smart-contracts/libraries/Oracle.en.md
          - TickMath: docs/smart-contracts/libraries/TickMath.en.md
          - Ticks: docs/smart-contracts/libraries/Tick.en.md
      - Utils:
          - MathUtils: docs/smart-contracts/libraries/Position.en.md
          - PoolsharkErrors: docs/smart-contracts/libraries/Position.en.md
          - RebaseLibrary: docs/smart-contracts/libraries/Position.en.md
          - SafeCast: docs/smart-contracts/libraries/SqrtPriceMath.en.md
          - SafeTransfers: docs/smart-contracts/libraries/UnsafeMath.en.md
          - UnsafeMath: docs/smart-contracts/libraries/UnsafeMath.en.md
      - Token Economy:
          - Centuplicate Mining: docs/smart-contracts/libraries/UnsafeMath.en.md
  # - Unique Features:
  #   - Default Positions:
  #       - Priority Queues: docs/fungible-queues/index.en.md
  #       - The Simple Explanation: docs/fungible-queues/the-simple-explanation.en.md
  #       - A Technical History: docs/fungible-queues/a-technical-history.en.md
  #       - QMM Core Concepts: docs/queued-market-making/index.en.md
  #       - Queuing Orders: docs/queued-market-making/set-liquidity.en.md
  #       - MEV Related Risks: docs/queued-market-making/mev-related-risks.en.md
  - References:
    - Limit Order Books: docs/references/limit-order-books.en.md
    - Automated Market Makers: docs/references/automated-market-makers.en.md
# - Tutorials:
#     - Basic Setup: docs/tutorials/basic-setup.en.md
#     - Swaps: 
#         - Single: docs/tutorials/swaps/single.en.md
#         - Multicall: docs/tutorials/swaps/multicall.en.md
#     - Liquidity: 
#         - Contract Setup: docs/tutorials/liquidity/contract-setup.en.md
#         - Mint Position: docs/tutorials/liquidity/mint-position.en.md
#         - Collect Fees: docs/tutorials/liquidity/collect-fees.en.md
#         - Modify Liquidity: docs/tutorials/liquidity/change-position.en.md
#     - Mining Incentives: docs/tutorials/liquidity/mining-incentives.en.md
#     - Flash Swaps: 
#         - Contract Setup: docs/tutorials/flash-swaps/contract-setup.en.md
#         - Execution: docs/tutorials/flash-swaps/execution.en.md
#         - Callback: docs/tutorials/flash-swaps/callback.en.md

 
  
  #   - For Takers: docs/fungible-queues/ingestion.en.md
  # - Design Tradeoffs: docs/design-tradeoffs/index.md
  #   - vs. AMMs: docs/design-tradeoffs/amms.en.md
  #   - vs. Off-Chain Orderbooks: docs/design-tradeoffs/off-chain-orderbooks.en.md
  #   - vs. CEX Orderbooks: docs/design-tradeoffs/cex-orderbooks.en.md
  # - Take Profit: docs/take-profit/index.en.md
  #   - Deposit Collateral: docs/modules/index.en.md
  #   - Borrow To Sell: docs/modules/base.en.md
  #   - Short Sell: docs/modules/predadex.en.md
  # - Short Sell:
  #   - What is a short sell?: docs/index.en.md
  #   - Short Sell on Poolshark:
  #     - Deposit Collateral: docs/modules/index.en.md
  #     - Borrow To Sell: docs/modules/base.en.md
  #     - Short Sell: docs/modules/predadex.en.md
  #     - Avoiding Liquidiations: docs/short-sell/avoid-liquidations.en.md
  

   # - JIT Liquidity: docs/queued-market-making/just-in-time-liquidity.en.md
    

theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo-removebg.png
  favicon: assets/images/Logo-removebg.png
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.attr_list
  - md_in_html

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    # - macros:
    #     include_dir: site/content/docs/include
