site_name: Documentation
# site_description: 'Develop, Release and Operate Container Apps on AWS.'
# site_url: 'https://aws.github.io/copilot-cli/'
repo_name: 'GitHub'
repo_url: 'https://github.com/poolsharks-protocol/DCEX-Docs'
edit_uri: 'tree/main/docs'
copyright: 'Copyright &copy; 2022 PoolSharks'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.en.md
  - Intro:
    - Overview: intro/index.en.md
    - Concepts:
      - Layers: intro/layers/index.en.md
      - User Interaction: intro/layers/user-interaction.en.md
      - Data Ingestion: intro/layers/ingestion.en.md
      - Data Queries: intro/layers/query.en.md
      - On Chain Execution: intro/layers/execution.en.md
      - Code Storage: intro/layers/code-storage.en.md
    - Security: intro/security.en.md
    - Conclusion: intro/conclusion.en.md
  - Documentation: docs/index.en.md
    # - Overview:
    # - Getting Started:
    # - Concepts:
    # - Developing:
    # - Commands:
    #   - Getting Started:
  # - Community:
      # - Get Involved: community/get-involved.en.md
      # - Guides and Resources: community/guides.en.md
theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo.svg
  favicon: assets/images/Logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    # - macros:
    #     include_dir: site/content/docs/include
