site_name: OceanBook Docs
# site_description: 'Develop, Release and Operate Container Apps on AWS.'
site_url: https://poolsharks-protocol.github.io/oceanbook-docs/
repo_name: 'GitHub'
repo_url: 'https://github.com/poolsharks-protocol/oceanbook-docs/'
edit_uri: '/poolsharks-protocol/DCEX-Docs/tree/main/site/content'
copyright: 'Written by PoolSharks Labs'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.en.md
  - Introduction: 
      - Overview: docs/intro/index.en.md
      - Launch Strategy: docs/intro/launch.en.md
  - Fungible Queues: 
      - Intro: docs/fungible-queues/index.en.md
      - The Simple Explanation: docs/fungible-queues/the-simple-explanation.en.md
      - A Technical History: docs/fungible-queues/a-technical-history.en.md
  #   - For Takers: docs/fungible-queues/ingestion.en.md
  # - Design Tradeoffs: docs/design-tradeoffs/index.md
  #   - vs. AMMs: docs/design-tradeoffs/amms.en.md
  #   - vs. Off-Chain Orderbooks: docs/design-tradeoffs/off-chain-orderbooks.en.md
  #   - vs. CEX Orderbooks: docs/design-tradeoffs/cex-orderbooks.en.md
  # - Take Profit: docs/take-profit/index.en.md
  #   - Deposit Collateral: docs/modules/index.en.md
  #   - Borrow To Sell: docs/modules/core.en.md
  #   - Short Sell: docs/modules/predadex.en.md
  # - Short Sell:
  #   - What is a short sell?: docs/index.en.md
  #   - Short Sell on OceanBook:
  #     - Deposit Collateral: docs/modules/index.en.md
  #     - Borrow To Sell: docs/modules/core.en.md
  #     - Short Sell: docs/modules/predadex.en.md
  #     - Avoiding Liquidiations: docs/short-sell/avoid-liquidations.en.md
  - Queued Market Making:
    - QMM Core Concepts: docs/queued-market-making/index.en.md
    - For Market Makers: docs/queued-market-making/set-liquidity.en.md

   # - JIT Liquidity: docs/queued-market-making/just-in-time-liquidity.en.md
   # - MEV Related Risks: docs/queued-market-making/mev-related-risks.en.md
  - References:
    - Limit Order Books: docs/references/limit-order-books.en.md
    - Automated Market Makers: docs/references/automated-market-makers.en.md
theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo.svg
  favicon: assets/images/Logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.attr_list

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    # - macros:
    #     include_dir: site/content/docs/include
