site_name: OceanBook Docs
# site_description: 'Develop, Release and Operate Container Apps on AWS.'
site_url: https://poolsharks-protocol.github.io/oceanbook-docs/
repo_name: 'GitHub'
repo_url: 'https://github.com/poolsharks-protocol/oceanbook-docs/'
edit_uri: '/poolsharks-protocol/DCEX-Docs/tree/main/site/content'
copyright: 'Written by PoolSharks Labs'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.en.md
  - Introduction: docs/intro/index.en.md
  - Protocol Guide:
    - Overview: docs/protocol-guide/index.en.md
    - Liquidity Types: 
        - Intro: docs/protocol-guide/index.en.md
        - Concentrated Liquidity: docs/liquidity-providers/double-sided.en.md
        - Directional Liquidity: docs/liquidity-providers/single-sided.en.md
        - Priority Queues: docs/fungible-queues/index.en.md
        - QMM Core Concepts: docs/queued-market-making/index.en.md
        - For Market Makers: docs/queued-market-making/set-liquidity.en.md
        - MEV Related Risks: docs/queued-market-making/mev-related-risks.en.md
        - The Simple Explanation: docs/fungible-queues/the-simple-explanation.en.md
        - A Technical History: docs/fungible-queues/a-technical-history.en.md
    - Oracles: docs/protocol-guide/oracles.en.md
    - MultiPage Orders: docs/protocol-guide/multipage-orders.en.md
    - Swaps: docs/protocol-guide/swaps.en.md
    - Fees: docs/protocol-guide/fees.en.md
    - References:
        - Limit Order Books: docs/references/limit-order-books.en.md
        - Automated Market Makers: docs/references/automated-market-makers.en.md
  - Tutorials:
      - Basic Setup: docs/tutorials/basic-setup.en.md
      - Swaps: 
          - Single: docs/tutorials/swaps/single.en.md
          - Multicall: docs/tutorials/swaps/multicall.en.md
      - Liquidity: 
          - Contract Setup: docs/tutorials/liquidity/contract-setup.en.md
          - Mint Position: docs/tutorials/liquidity/mint-position.en.md
          - Collect Fees: docs/tutorials/liquidity/collect-fees.en.md
          - Modify Liquidity: docs/tutorials/liquidity/change-position.en.md
      - Mining Incentives: docs/tutorials/liquidity/mining-incentives.en.md
      - Flash Swaps: 
          - Contract Setup: docs/tutorials/flash-swaps/contract-setup.en.md
          - Execution: docs/tutorials/flash-swaps/execution.en.md
          - Callback: docs/tutorials/flash-swaps/callback.en.md
  - Smart Contracts:
      - Overview: docs/smart-contracts/overview.en.md
      - Solidity Core: 
          - OceanBookFactory20: docs/smart-contracts/core/oceanbookfactory20.en.md
          - OceanBook20: docs/smart-contracts/core/oceanbook20.en.md
          - OceanBookRouter20: docs/smart-contracts/core/oceanbookrouter20.en.md
          - Interfacing With: docs/smart-contracts/core/interfacing-with.en.md
          - Libraries: docs/smart-contracts/core/libraries.en.md

 
  
  #   - For Takers: docs/fungible-queues/ingestion.en.md
  # - Design Tradeoffs: docs/design-tradeoffs/index.md
  #   - vs. AMMs: docs/design-tradeoffs/amms.en.md
  #   - vs. Off-Chain Orderbooks: docs/design-tradeoffs/off-chain-orderbooks.en.md
  #   - vs. CEX Orderbooks: docs/design-tradeoffs/cex-orderbooks.en.md
  # - Take Profit: docs/take-profit/index.en.md
  #   - Deposit Collateral: docs/modules/index.en.md
  #   - Borrow To Sell: docs/modules/core.en.md
  #   - Short Sell: docs/modules/predadex.en.md
  # - Short Sell:
  #   - What is a short sell?: docs/index.en.md
  #   - Short Sell on OceanBook:
  #     - Deposit Collateral: docs/modules/index.en.md
  #     - Borrow To Sell: docs/modules/core.en.md
  #     - Short Sell: docs/modules/predadex.en.md
  #     - Avoiding Liquidiations: docs/short-sell/avoid-liquidations.en.md
  

   # - JIT Liquidity: docs/queued-market-making/just-in-time-liquidity.en.md
    

theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo.svg
  favicon: assets/images/Logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.attr_list
  - md_in_html

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    # - macros:
    #     include_dir: site/content/docs/include
