site_name: PoolSharks Docs
# site_description: 'Develop, Release and Operate Container Apps on AWS.'
# site_url: 'https://aws.github.io/copilot-cli/'
site_url: https://poolsharks-protocol.github.io/DCEX-Docs/
repo_name: 'GitHub'
repo_url: 'https://github.com/poolsharks-protocol/DCEX-Docs'
edit_uri: '/poolsharks-protocol/DCEX-Docs/tree/main/site/content'
copyright: 'Copyright &copy; 2022 PoolSharks'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    # - name: 日本語
    #   link: ./ja/
    #   lang: ja
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.en.md
  - Intro:
    - Overview: docs/intro/index.en.md
    - Improvements: docs/intro/improvements.en.md
  - Fungible Queues: docs/fungible-queues/index.en.md
    - For Market Makers: docs/fungible-queues/user-interaction.en.md
    - For Takers: docs/fungible-queues/ingestion.en.md
  - Design Tradeoffs: docs/design-tradeoffs/index.md
    - vs. AMMs: docs/design-tradeoffs/amms.en.md
    - vs. Off-Chain Orderbooks: docs/design-tradeoffs/off-chain-orderbooks.en.md
    - vs. CEX Orderbooks: docs/design-tradeoffs/cex-orderbooks.en.md
  - Take Profit: docs/take-profit/index.en.md
    - Deposit Collateral: docs/modules/index.en.md
    - Borrow To Sell: docs/modules/core.en.md
    - Short Sell: docs/modules/predadex.en.md
  - Short Sell:
    - What is a short sell?: docs/index.en.md
    - Short Sell on OceanBook:
      - Deposit Collateral: docs/modules/index.en.md
      - Borrow To Sell: docs/modules/core.en.md
      - Short Sell: docs/modules/predadex.en.md
      - Avoiding Liquidiations: docs/short-sell/avoid-liquidations.en.md
  - Queued Market Making:
    - Fee Collection
    - JIT Liquidity
    - MEV Related Risks
  - References:
    - Limit Order Books
    - Automated Market Makers
theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  logo: assets/images/Logo.svg
  favicon: assets/images/Logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - abbr
  - admonition
  - tables
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    - i18n:
        default_language: en
        languages:
          en: english
          # ja: japanese
        material_alternate: false
    # - macros:
    #     include_dir: site/content/docs/include
